version: '3.8'

name: banking

services:
  quarks-app:
    container_name: banking-quarkus-app
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: banking-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  postgres_volume:
