version: '3.8'

name: banking

services:
  quarks-app:
    container_name: banking-quarkus-app
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
